-- MySQL Script generated by MySQL Workbench
-- Срд 01 лют 2023 19:14:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `PassengerId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `cityCode` INT NULL,
  `birthDate` DATE NULL,
  `passportInfo` VARCHAR(45) NULL,
  `passwordEndDate` DATE NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`PassengerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `book_id` INT NOT NULL,
  `book_date` DATETIME NULL,
  `total_book_ammount` INT NULL,
  `status` TINYINT NULL,
  `Passenger_PassengerId` INT NOT NULL,
  PRIMARY KEY (`book_id`, `Passenger_PassengerId`),
  INDEX `fk_Booking_Passenger1_idx` (`Passenger_PassengerId` ASC),
  CONSTRAINT `fk_Booking_Passenger1`
    FOREIGN KEY (`Passenger_PassengerId`)
    REFERENCES `mydb`.`Passenger` (`PassengerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  `airports_ammount` VARCHAR(45) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airports` (
  `airport_id` INT NOT NULL,
  `airport_name` VARCHAR(45) NULL,
  `longtitude` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `timezone` DATETIME NULL,
  `city_city_id` INT NOT NULL,
  PRIMARY KEY (`airport_id`),
  INDEX `fk_Airports_city1_idx` (`city_city_id` ASC),
  CONSTRAINT `fk_Airports_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airplanes` (
  `airplane_id` INT NOT NULL,
  `model` VARCHAR(45) NULL,
  `range` VARCHAR(45) NULL,
  `classASeatsAmount` INT NULL,
  `classBSeatsAmount` INT NULL,
  `classCSeatsAmount` INT NULL,
  PRIMARY KEY (`airplane_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AviaCompany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AviaCompany` (
  `idAviaCompany` INT NOT NULL,
  `AviaCompanyName` VARCHAR(45) NULL,
  PRIMARY KEY (`idAviaCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `flight_id` INT NOT NULL,
  `forwardingTime` DATETIME NULL,
  `arrivingTime` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `Airports_airport_id` INT NOT NULL,
  `Airports_airport_id1` INT NOT NULL,
  `airplanes_airplane_id` INT NOT NULL,
  `AviaCompany_idAviaCompany` INT NOT NULL,
  PRIMARY KEY (`flight_id`, `AviaCompany_idAviaCompany`),
  INDEX `fk_Flight_Airports1_idx` (`Airports_airport_id` ASC),
  INDEX `fk_Flight_Airports2_idx` (`Airports_airport_id1` ASC),
  INDEX `fk_Flight_airplanes1_idx` (`airplanes_airplane_id` ASC),
  INDEX `fk_Flight_AviaCompany1_idx` (`AviaCompany_idAviaCompany` ASC),
  CONSTRAINT `fk_Flight_Airports1`
    FOREIGN KEY (`Airports_airport_id`)
    REFERENCES `mydb`.`Airports` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airports2`
    FOREIGN KEY (`Airports_airport_id1`)
    REFERENCES `mydb`.`Airports` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_airplanes1`
    FOREIGN KEY (`airplanes_airplane_id`)
    REFERENCES `mydb`.`airplanes` (`airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_AviaCompany1`
    FOREIGN KEY (`AviaCompany_idAviaCompany`)
    REFERENCES `mydb`.`AviaCompany` (`idAviaCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forwarding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forwarding` (
  `forwarding_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `forwardingTime` DATETIME NULL,
  `arrivingTime` DATETIME NULL,
  `actualForwardingTime` DATETIME NULL,
  `actualArrivingTime` DATETIME NULL,
  `continuance` TIME NULL,
  `Flight_flight_id` INT NOT NULL,
  PRIMARY KEY (`forwarding_id`, `Flight_flight_id`),
  INDEX `fk_Forwarding_Flight1_idx` (`Flight_flight_id` ASC),
  CONSTRAINT `fk_Forwarding_Flight1`
    FOREIGN KEY (`Flight_flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Ticket_id` INT NOT NULL,
  `Passenger_name` VARCHAR(45) NULL,
  `Passenger_PassengerId` INT NOT NULL,
  `Booking_book_id` INT NOT NULL,
  `Booking_Passenger_PassengerId` INT NOT NULL,
  `Forwarding_forwarding_id` INT NOT NULL,
  `Forwarding_Flight_flight_id` INT NOT NULL,
  PRIMARY KEY (`Ticket_id`, `Passenger_PassengerId`, `Booking_book_id`, `Booking_Passenger_PassengerId`, `Forwarding_forwarding_id`, `Forwarding_Flight_flight_id`),
  INDEX `fk_Tickets_Passenger1_idx` (`Passenger_PassengerId` ASC),
  INDEX `fk_Tickets_Booking1_idx` (`Booking_book_id` ASC, `Booking_Passenger_PassengerId` ASC),
  INDEX `fk_Ticket_Forwarding1_idx` (`Forwarding_forwarding_id` ASC, `Forwarding_Flight_flight_id` ASC),
  CONSTRAINT `fk_Tickets_Passenger1`
    FOREIGN KEY (`Passenger_PassengerId`)
    REFERENCES `mydb`.`Passenger` (`PassengerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Booking1`
    FOREIGN KEY (`Booking_book_id` , `Booking_Passenger_PassengerId`)
    REFERENCES `mydb`.`Booking` (`book_id` , `Passenger_PassengerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Forwarding1`
    FOREIGN KEY (`Forwarding_forwarding_id` , `Forwarding_Flight_flight_id`)
    REFERENCES `mydb`.`Forwarding` (`forwarding_id` , `Flight_flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket_flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket_flight` (
  `ticketFlight_id` INT NOT NULL,
  `fare_conditions` VARCHAR(45) NULL,
  `ammount` INT NULL,
  `Tickets_Tickets` INT NOT NULL,
  `Tickets_Passenger_PassengerId` INT NOT NULL,
  `Tickets_Booking_book_id` INT NOT NULL,
  `Tickets_Booking_Passenger_PassengerId` INT NOT NULL,
  PRIMARY KEY (`ticketFlight_id`, `Tickets_Tickets`, `Tickets_Passenger_PassengerId`, `Tickets_Booking_book_id`, `Tickets_Booking_Passenger_PassengerId`),
  INDEX `fk_Ticket_flights_Tickets1_idx` (`Tickets_Tickets` ASC, `Tickets_Passenger_PassengerId` ASC, `Tickets_Booking_book_id` ASC, `Tickets_Booking_Passenger_PassengerId` ASC),
  CONSTRAINT `fk_Ticket_flights_Tickets1`
    FOREIGN KEY (`Tickets_Tickets` , `Tickets_Passenger_PassengerId` , `Tickets_Booking_book_id` , `Tickets_Booking_Passenger_PassengerId`)
    REFERENCES `mydb`.`Ticket` (`Ticket_id` , `Passenger_PassengerId` , `Booking_book_id` , `Booking_Passenger_PassengerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seats` (
  `airplane_id` INT NOT NULL,
  `seat_no` INT NULL,
  `airplanes_airplane_id` INT NOT NULL,
  `class` CHAR NULL,
  PRIMARY KEY (`airplane_id`, `airplanes_airplane_id`),
  INDEX `fk_seats_airplanes1_idx` (`airplanes_airplane_id` ASC),
  CONSTRAINT `fk_seats_airplanes1`
    FOREIGN KEY (`airplanes_airplane_id`)
    REFERENCES `mydb`.`airplanes` (`airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boarding_passes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boarding_passes` (
  `baggage_weight` INT NULL,
  `baggage_volume` INT NULL,
  `seats_airplane_id` INT NOT NULL,
  `seats_airplanes_airplane_id` INT NOT NULL,
  `Ticket_flights_ticketFlight_id` INT NOT NULL,
  `Ticket_flights_Tickets_Tickets` INT NOT NULL,
  `Ticket_flights_Tickets_Passenger_PassengerId` INT NOT NULL,
  `Ticket_flights_Tickets_Booking_book_id` INT NOT NULL,
  `Ticket_flights_Tickets_Booking_Passenger_PassengerId` INT NOT NULL,
  PRIMARY KEY (`seats_airplanes_airplane_id`, `seats_airplane_id`),
  INDEX `fk_Boarding_passes_seats1_idx` (`seats_airplane_id` ASC, `seats_airplanes_airplane_id` ASC),
  INDEX `fk_Boarding_passes_Ticket_flights1_idx` (`Ticket_flights_ticketFlight_id` ASC, `Ticket_flights_Tickets_Tickets` ASC, `Ticket_flights_Tickets_Passenger_PassengerId` ASC, `Ticket_flights_Tickets_Booking_book_id` ASC, `Ticket_flights_Tickets_Booking_Passenger_PassengerId` ASC),
  CONSTRAINT `fk_Boarding_passes_seats1`
    FOREIGN KEY (`seats_airplane_id` , `seats_airplanes_airplane_id`)
    REFERENCES `mydb`.`seats` (`airplane_id` , `airplanes_airplane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boarding_passes_Ticket_flights1`
    FOREIGN KEY (`Ticket_flights_ticketFlight_id` , `Ticket_flights_Tickets_Tickets` , `Ticket_flights_Tickets_Passenger_PassengerId` , `Ticket_flights_Tickets_Booking_book_id` , `Ticket_flights_Tickets_Booking_Passenger_PassengerId`)
    REFERENCES `mydb`.`Ticket_flight` (`ticketFlight_id` , `Tickets_Tickets` , `Tickets_Passenger_PassengerId` , `Tickets_Booking_book_id` , `Tickets_Booking_Passenger_PassengerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
